---
name: Deploy Azure TRE (Bundle)
# This workflow is the integration build run for pushes to the main branch
# It also runs on a schedule, serving as the nightly build

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to run this workflow in
        type: environment
        default: Dev
        required: true
      templateVersion:
        type: choice
        description: Template Version
        options:
          - stable
          - beta
      bundleType:
        type: choice
        description: Bundle Type
        options:
          - workspace
          - workspace_service
          - user_resource
          - shared_service
      bundleDir:
        type: choice
        description: Bundle Dir
        options:
          - workspaces
          - workspace_services
          - user_resources
          - shared_services
      bundleName:
        type: string
        description: Bundle Name

      # bundleDir:
      #   type: string
      #   description: Bundle Directory e.g. ./templates/workspaces/base
      #   default: ./templates/stable/workspaces/airlock-import-review
      workspaceName:
        type: string
        description: Workspace Name (Required if type is user_resource) tre-service-...

# This will prevent multiple runs of this entire workflow.
# We should NOT cancel in progress runs as that can destabilize the environment.
concurrency: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  run-deploy-tre-bundle:
    name: "Deploy Bundle"
    # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    uses: ./.github/workflows/deploy_tre_reusable_bundle.yml
    with:
      ciGitRef: ${{ github.ref }}
      e2eTestsCustomSelector: >-
        ${{ (github.event_name == 'push' && 'extended or extended_aad')
        || 'extended or extended_aad or shared_services or airlock' }}
      environmentName: ${{ github.event.inputs.environment || 'CICD' }}
      E2E_TESTS_NUMBER_PROCESSES: 1
      DEVCONTAINER_TAG: "latest"
      bundleType: ${{ inputs.bundleType }}
      bundleDir: "./templates/${{ inputs.templateVersion }}/${{ inputs.bundleDir }}/${{ inputs.bundleName }}"
      workspaceName: ${{ inputs.workspaceName }}
    secrets:
      AAD_TENANT_ID: ${{ secrets.AAD_TENANT_ID }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
      API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
      APPLICATION_ADMIN_CLIENT_ID: ${{ secrets.APPLICATION_ADMIN_CLIENT_ID }}
      APPLICATION_ADMIN_CLIENT_SECRET: ${{ secrets.APPLICATION_ADMIN_CLIENT_SECRET }}
      MGMT_RESOURCE_GROUP_NAME: ${{ secrets.MGMT_RESOURCE_GROUP_NAME }}
      MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      MGMT_STORAGE_ACCOUNT_NAME: ${{ secrets.MGMT_STORAGE_ACCOUNT_NAME }}
      SWAGGER_UI_CLIENT_ID: ${{ secrets.SWAGGER_UI_CLIENT_ID }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
      TEST_WORKSPACE_APP_ID: ${{ secrets.TEST_WORKSPACE_APP_ID }}
      TEST_WORKSPACE_APP_SECRET: "${{ secrets.TEST_WORKSPACE_APP_SECRET }}"
      TEST_ACCOUNT_CLIENT_ID: "${{ secrets.TEST_ACCOUNT_CLIENT_ID }}"
      TEST_ACCOUNT_CLIENT_SECRET: "${{ secrets.TEST_ACCOUNT_CLIENT_SECRET }}"
      TRE_ID: ${{ secrets.TRE_ID }}
      CI_CACHE_ACR_NAME: ${{ secrets.ACR_NAME }}
